const ENGLISH_TO_HINDI: Record<string, string> = {
  aadhaar: "आधार",
  "aadhaar card": "आधार कार्ड",
  card: "कार्ड",
  registration: "पंजीकरण",
  apply: "आवेदन",
  "apply for": "आवेदन करें",
  update: "अपडेट",
  create: "बनाएं",
  new: "नया",
  search: "खोजें",
  find: "खोजें",
  check: "जांचें",
  view: "देखें",
  download: "डाउनलोड",
  payment: "भुगतान",
  pay: "भरें",
  bill: "बिल",
  status: "स्थिति",
  details: "विवरण",
  information: "जानकारी",
  help: "सहायता",
  helpline: "हेल्पलाइन",
  service: "सेवा",
  services: "सेवाएं",
  government: "सरकारी",
  portal: "पोर्टल",
  login: "लॉगिन",
  logout: "लॉगआउट",
  dashboard: "डैशबोर्ड",
  settings: "सेटिंग्स",
  admin: "एडमिन",
  home: "होम",
  about: "परिचय",
  contact: "संपर्क",
  feedback: "फीडबैक",
  complaint: "शिकायत",
  grievance: "शिकायत",
  scheme: "योजना",
  schemes: "योजनाएं",
  loan: "लोन",
  subsidy: "सब्सिडी",
  farmer: "किसान",
  pension: "पेंशन",
  employment: "रोजगार",
  job: "नौकरी",
  jobs: "नौकरियां",
  certificate: "प्रमाणपत्र",
  land: "भूमि",
  record: "रिकॉर्ड",
  voter: "वोटर",
  election: "चुनाव",
  driving: "ड्राइविंग",
  license: "लाइसेंस",
  vehicle: "वाहन",
  pan: "पैन",
  passport: "पासपोर्ट",
  digilocker: "डिजिलॉकर",
  umang: "उमंग",
  edistrict: "इडिस्ट्रिक्ट",
  ration: "राशन",
  electricity: "बिजली",
  sim: "सिम",
  mobile: "मोबाइल",
  recharge: "रिचार्ज",
  plan: "प्लान",
  tariff: "टैरिफ",
  kyc: "केवाईसी",
  imei: "आईएमईआई",
  block: "ब्लॉक",
  track: "ट्रैक",
  lost: "खोया",
  challan: "चालान",
  fastag: "फास्टैग",
  mudra: "मुद्रा",
  startup: "स्टार्टअप",
  rtI: "आरटीआई",
  right: "अधिकार",
  epfo: "ईपीएफओ",
  pf: "पीएफ",
  provident: "प्रोविडेंट",
  fund: "फंड",
  balance: "बैलेंस",
  jeevan: "जीवन",
  pramaan: "प्रमाण",
  digital: "डिजिटल",
  locker: "लॉकर",
  ncs: "एनसीएस",
  career: "कैरियर",
  ayushman: "आयुष्मान",
  bharat: "भारत",
  pm: "पीएम",
  kisan: "किसान",
  samman: "सम्मान",
  nidhi: "निधि",
  awas: "आवास",
  yojana: "योजना",
  ujjwala: "उज्ज्वला",
  gas: "गैस",
  connection: "कनेक्शन",
  surya: "सूर्य",
  ghar: "घर",
  solar: "सोलर",
  panel: "पैनल",
  vishwakarma: "विश्वकर्मा",
  artisan: "कारीगर",
  support: "सहायता",
  nfsa: "एनएफएसए",
  food: "खाद्य",
  security: "सुरक्षा",
  eshram: "ई-श्रम",
  labour: "श्रमिक",
  worker: "श्रमिक",
  unorganised: "असंगठित",
  sector: "क्षेत्र",
  health: "स्वास्थ्य",
  insurance: "बीमा",
  treatment: "इलाज",
  lakh: "लाख",
  free: "मुफ्त",
  ad: "विज्ञापन",
  ads: "विज्ञापन",
  category: "श्रेणी",
  categories: "श्रेणियां",
  link: "लिंक",
  links: "लिंक",
  url: "यूआरएल",
  website: "वेबसाइट",
  web: "वेब",
  site: "साइट",
  page: "पेज",
  online: "ऑनलाइन",
  offline: "ऑफलाइन",
  form: "फॉर्म",
  submit: "जमा करें",
  submitted: "जमा किया गया",
  success: "सफलता",
  error: "त्रुटि",
  warning: "चेतावनी",
  alert: "अलर्ट",
  notification: "सूचना",
  message: "संदेश",
  mail: "मेल",
  email: "ईमेल",
  phone: "फोन",
  number: "नंबर",
  address: "पता",
  name: "नाम",
  date: "तिथि",
  time: "समय",
  day: "दिन",
  month: "महीना",
  year: "वर्ष",
  birth: "जन्म",
  death: "मृत्यु",
  marriage: "विवाह",
  income: "आय",
  caste: "जाति",
  domicile: "निवास",
  residence: "निवास",
  resident: "निवासी",
  divorce: "तलाक",
  widow: "विधवा",
  senior: "वरिष्ठ",
  citizen: "नागरिक",
  citizenship: "नागरिकता",
  visa: "वीजा",
  immigration: "आप्रवासन",
  emigration: "प्रवासन",
  overseas: "विदेशी",
  foreign: "विदेशी",
  opportunity: "अवसर",
  skill: "कौशल",
  training: "प्रशिक्षण",
  education: "शिक्षा",
  school: "विद्यालय",
  college: "महाविद्यालय",
  university: "विश्वविद्यालय",
  degree: "डिग्री",
  diploma: "डिप्लोमा",
  course: "पाठ्यक्रम",
  exam: "परीक्षा",
  result: "परिणाम",
  marks: "अंक",
  grade: "ग्रेड",
  scholarship: "छात्रवृत्ति",
  student: "छात्र",
  teacher: "शिक्षक",
  staff: "कर्मचारी",
  employee: "कर्मचारी",
  employer: "नियोक्ता",
  recruitment: "भर्ती",
  vacancy: "रिक्ति",
  interview: "इंटरव्यू",
  test: "परीक्षण",
  written: "लिखित",
  physical: "शारीरिक",
  medical: "चिकित्सा",
  document: "दस्तावेज",
  proof: "प्रमाण",
  verify: "सत्यापन",
  verification: "सत्यापन",
  authenticate: "प्रमाणित",
  authentication: "प्रमाणीकरण",
  authorization: "प्राधिकरण",
  authorize: "अधिकृत",
  approve: "अनुमोदन",
  reject: "अस्वीकार",
  pending: "लंबित",
  processing: "प्रसंस्करण",
  complete: "पूर्ण",
  cancel: "रद्द",
  delete: "हटाएं",
  remove: "हटाएं",
  edit: "संपादित",
  change: "बदलें",
  save: "सहेजें",
  reset: "रीसेट",
  refresh: "रिफ्रेश",
  reload: "रीलोड",
  back: "वापस",
  next: "अगला",
  total: "कुल",
  count: "गणना",
  serial: "क्रम",
  order: "क्रम",
  sort: "क्रमबद्ध",
  filter: "फिल्टर",
  query: "क्वेरी",
  report: "रिपोर्ट",
  export: "निर्यात",
  import: "आयात",
  print: "प्रिंट",
  upload: "अपलोड",
  file: "फाइल",
  folder: "फोल्डर",
  directory: "डिरेक्टरी",
  path: "पथ",
  location: "स्थान",
  code: "कोड",
  type: "प्रकार",
  group: "समूह",
  team: "टीम",
  department: "विभाग",
  office: "कार्यालय",
  organization: "संगठन",
  ministry: "मंत्रालय",
  state: "राज्य",
  central: "केंद्रीय",
  national: "राष्ट्रीय",
  international: "अंतर्राष्ट्रीय",
  local: "स्थानीय",
  rural: "ग्रामीण",
  urban: "शहरी",
  village: "ग्राम",
  city: "शहर",
  district: "जिला",
  country: "देश",
  world: "दुनिया",
  global: "वैश्विक",
};

const HINDI_TO_ENGLISH: Record<string, string> = Object.fromEntries(
  Object.entries(ENGLISH_TO_HINDI).map(([en, hi]) => [hi, en])
);

function transliterateWord(word: string): string {
  const lower = word.toLowerCase();
  if (ENGLISH_TO_HINDI[lower]) {
    return ENGLISH_TO_HINDI[lower];
  }
  return word;
}

function reverseWord(word: string): string {
  const trimmed = word.trim();
  if (HINDI_TO_ENGLISH[trimmed]) {
    return HINDI_TO_ENGLISH[trimmed];
  }
  return word;
}

export function toHindi(text: string): string {
  if (!text) return text;
  const parts = text.split(/[\s.,!?;:()[\]{}'"\/\\|<>@#$%^&*\-+=~`]+/);
  return parts.map((part) => transliterateWord(part)).join("");
}

export function toEnglish(text: string): string {
  if (!text) return text;
  const parts = text.split(/[\s.,!?;:()[\]{}'"\/\\|<>@#$%^&*\-+=~`]+/);
  return parts.map((part) => reverseWord(part)).join("");
}

export function toHindiField(value: string): string {
  return toHindi(value);
}

export function toEnglishField(value: string): string {
  return toEnglish(value);
}

export function syncBidirectional(
  value: string,
  sourceLang: "en" | "hi",
  targetLang: "en" | "hi"
): string {
  if (sourceLang === targetLang) return value;
  if (sourceLang === "en" && targetLang === "hi") {
    return toHindi(value);
  }
  if (sourceLang === "hi" && targetLang === "en") {
    return toEnglish(value);
  }
  return value;
}
